#!/bin/bash

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PRJDIR="$THISDIR/app"
ENV="hack"

set -euo pipefail

function build_help() {
cat <<ENDHELP
       build [cmd]
       Build commands for "$THISDIR"
           setup        Check your enviroment has the right requirements
           restore      Creates or updates your venv with your requirements.txt
           build        Run static analyis (mypy) and linting
           default      Setup, Restore, Build, citest
           migrate      Remove your .db file and runs schema
           seed         Populates the database with fake data made with faker
           citest       Runs pytest to test the flask endpoints
           dev          Runs a development flask server
        After clone, run setup
        After checkout or pull run restore
        Before commit run default
ENDHELP
}

function build_build() {
    (
        cd "$THISDIR"
        flake8 "$PRJDIR" && echo "Passed Flake8"
    )
    mypy ./app/*.py ./app/**/*.py --config-file "$THISDIR/mypy.ini"
}

function build_citest() {
    run_cmd seed
     pytest -vv
}

function build_test() {
    ./test
}

function build_restore() {
    if ! which python | grep -w "$ENV" > /dev/null ; then
        python3 -m venv "$ENV"
    fi
    source "$ENV/bin/activate"
    # pip install -r requirements.txt
}

function run_cmd() {
    local script=$1
    shift
    printf '==== %-10s    ====\n' "$script"
    "build_$script" "$@"
}

function build_default() {
    run_cmd setup
    run_cmd restore
    run_cmd build
    run_cmd citest
}

function build_setup() {
    command python --version > /dev/null || { echo "Missing python - you need to install it." ; exit 1 ; }
    command virtualenv --version > /dev/null || { echo "Missing virtualenv - you need to install it." ; exit 1 ; }
    command pip --version > /dev/null || { echo "Missing pip - you need to install it." ; exit 2 ; }
}

function build_dev() {
    : # python ./run.py
}

cmd="${1:-default}"
shift || true
"build_$cmd" "$@"
