#!/bin/bash

set -euo pipefail

echo "test fill"
./tools/CPUEmulator.sh ./project-data/04-machine-language/fill/FillAutomatic.tst
# echo "test mult"
# ./tools/CPUEmulator.sh ./project-data/04-machine-language/mult/Mult.tst

echo "test add"
./tools/Assembler.sh ./project-data/06-assembler/add/Add.asm
mv .hack ./project-data/06-assembler/add/javaAdd.hack
python project/assembler/assembler.py \
    ./project-data/06-assembler/add/Add.asm \
    -o ./project-data/06-assembler/add/Add.hack
git diff --no-index ./project-data/06-assembler/add/Add.hack ./project-data/06-assembler/add/javaAdd.hack
# ./tools/CPUEmulator.sh ./project-data/06-assembler/add/Add.tst

echo "test max"
./tools/Assembler.sh ./project-data/06-assembler/max/Max.asm
mv .hack ./project-data/06-assembler/max/javaMax.hack
python project/assembler/assembler.py \
    ./project-data/06-assembler/max/Max.asm \
    -o ./project-data/06-assembler/max/Max.hack
git diff --no-index ./project-data/06-assembler/max/Max.hack ./project-data/06-assembler/max/javaMax.hack

echo "test pong"
./tools/Assembler.sh ./project-data/06-assembler/pong/Pong.asm
mv .hack ./project-data/06-assembler/pong/javaPong.hack
python project/assembler/assembler.py \
    ./project-data/06-assembler/pong/Pong.asm \
    -o ./project-data/06-assembler/pong/Pong.hack
git diff --no-index ./project-data/06-assembler/pong/Pong.hack ./project-data/06-assembler/pong/javaPong.hack

echo "test rect"
./tools/Assembler.sh ./project-data/06-assembler/rect/Rect.asm
mv .hack ./project-data/06-assembler/rect/javaRect.hack
python project/assembler/assembler.py \
    ./project-data/06-assembler/rect/Rect.asm \
    -o ./project-data/06-assembler/rect/Rect.hack
git diff --no-index ./project-data/06-assembler/rect/Rect.hack ./project-data/06-assembler/rect/javaRect.hack

echo "test vm1/basicTest"
python project/virtual-machine1/vm-code-writer.py ./project-data/07-vm1/MemoryAccess/BasicTest/BasicTest.vm
mv ./BasicTest.asm ./project-data/07-vm1/MemoryAccess/BasicTest/BasicTest.asm
./tools/CPUEmulator.sh ./project-data/07-vm1/MemoryAccess/BasicTest/BasicTest.tst

echo "test vm1/PointerTest"
python project/virtual-machine1/vm-code-writer.py ./project-data/07-vm1/MemoryAccess/PointerTest/PointerTest.vm
mv ./PointerTest.asm ./project-data/07-vm1/MemoryAccess/PointerTest/PointerTest.asm
./tools/CPUEmulator.sh ./project-data/07-vm1/MemoryAccess/PointerTest/PointerTest.tst

echo "test vm1/StaticTest"
python project/virtual-machine1/vm-code-writer.py ./project-data/07-vm1/MemoryAccess/StaticTest/StaticTest.vm
mv ./StaticTest.asm ./project-data/07-vm1/MemoryAccess/StaticTest/StaticTest.asm
./tools/CPUEmulator.sh ./project-data/07-vm1/MemoryAccess/StaticTest/StaticTest.tst

echo "test vm1/SimpleAdd"
python project/virtual-machine1/vm-code-writer.py ./project-data/07-vm1/StackArithmetic/SimpleAdd/SimpleAdd.vm
mv ./SimpleAdd.asm ./project-data/07-vm1/StackArithmetic/SimpleAdd/SimpleAdd.asm
./tools/CPUEmulator.sh ./project-data/07-vm1/StackArithmetic/SimpleAdd/SimpleAdd.tst

echo "test vm1/StackTest"
python project/virtual-machine1/vm-code-writer.py ./project-data/07-vm1/StackArithmetic/StackTest/StackTest.vm
mv ./StackTest.asm ./project-data/07-vm1/StackArithmetic/StackTest/StackTest.asm
./tools/CPUEmulator.sh ./project-data/07-vm1/StackArithmetic/StackTest/StackTest.tst

echo "test vm2/NestedCall"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/FunctionCalls/NestedCall
mv ./NestedCall.asm ./project-data/08-vm2/FunctionCalls/NestedCall/NestedCall.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/FunctionCalls/NestedCall/NestedCall.tst

echo "test vm2/SimpleFunction"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/FunctionCalls/SimpleFunction
mv ./SimpleFunction.asm ./project-data/08-vm2/FunctionCalls/SimpleFunction/SimpleFunction.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/FunctionCalls/SimpleFunction/SimpleFunction.tst

echo "test vm2/StaticsTest"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/FunctionCalls/StaticsTest
mv ./StaticsTest.asm ./project-data/08-vm2/FunctionCalls/SimpleFunction/StaticsTest.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/FunctionCalls/StaticsTest/StaticsTest.tst

echo "test vm2/BasicLoop"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/ProgramFlow/BasicLoop
mv ./BasicLoop.asm ./project-data/08-vm2/ProgramFlow/BasicLoop/BasicLoop.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/ProgramFlow/BasicLoop/BasicLoop.tst

echo "test vm2/FibonacciSeries"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/ProgramFlow/FibonacciSeries
mv ./FibonacciSeries.asm ./project-data/08-vm2/ProgramFlow/FibonacciSeries/FibonacciSeries.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/ProgramFlow/FibonacciSeries/FibonacciSeries.tst

echo "test vm2/FibonacciElement"
python project/virtual-machine1/vm-code-writer.py ./project-data/08-vm2/FunctionCalls/FibonacciElement
mv ./FibonacciElement.asm ./project-data/08-vm2/FunctionCalls/FibonacciElement/FibonacciElement.asm
./tools/CPUEmulator.sh ./project-data/08-vm2/FunctionCalls/FibonacciElement/FibonacciElement.tst
